<a href="https://colab.research.google.com/github/JinaaK/mulcamp34/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Google Colab과 Google Drive 연동
- 인증 확인 절차

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
import pandas as pd
DATA_PATH = '/content/drive/MyDrive/Colab Notebooks/멀티캠퍼스34/playground-series-s4e1/'
train = pd.read_csv(DATA_PATH + 'train.csv')
train

,id,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,0,15674932,Okwudilichukwu,668,France,Male,33.0,3,0.00,2,1.0,0.0,181449.97,0
1,1,15749177,Okwudiliolisa,627,France,Male,33.0,1,0.00,2,1.0,1.0,49503.50,0
2,2,15694510,Hsueh,678,France,Male,40.0,10,0.00,2,1.0,0.0,184866.69,0
3,3,15741417,Kao,581,France,Male,34.0,2,148882.54,1,1.0,1.0,84560.88,0
4,4,15766172,Chiemenam,716,Spain,Male,33.0,5,0.00,2,1.0,1.0,15068.83,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165029,165029,15667085,Meng,667,Spain,Female,33.0,2,0.00,1,1.0,1.0,131834.75,0
165030,165030,15665521,Okechukwu,792,France,Male,35.0,3,0.00,1,0.0,0.0,131834.45,0
165031,165031,15664752,Hsia,565,France,Male,31.0,5,0.00,1,1.0,1.0,127429.56,0
165032,165032,15689614,Hsiung,554,Spain,Female,30.0,7,161533.00,1,0.0,1.0,71173.03,0
165033,165033,15732798,Ulyanov,850,France,Male,31.0,1,0.00,1,1.0,0.0,61581.79,1

- 파일 내보내기
- 컬럼 임의로 몇개 선정 후, playground에 csv로 내보내기
  + 파일명 : result.csv

In [6]:
result = train.loc[:, ['id', 'Age']]
result.to_csv(DATA_PATH + "result11.csv", index=False) # index=False 시, index 번호는 열로 추출 안함

# 첫번째, 프로젝트 폴더 내로 내보내기가 된다. result.to_csv("result11.csv", index=False)
# 두번째, playground~~ 폴더로 내보내기가 된다.
DATA_PATH + "result.csv"

'/content/drive/MyDrive/Colab Notebooks/멀티캠퍼스34/playground-series-s4e1/result.csv'